name: producer-consumer

services:
  rabbitmq:
    image: rabbitmq:4.3.2-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "15672:15672"
      - "5672:5672"
  
  postgres:
    image: postgres:18
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER}
    volumes:
      - pgdata:/var/lib/postgresql

  producer:
    image: producer
    build:
      context: .
      dockerfile: src/Producer/Dockerfile
      tags:
        - latest
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: ${RABBITMQ_USERNAME}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}

volumes:
  pgdata: